version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"

    # If you are on arm64 and experiencing issues with the tests (hangs,
    # connection reset) then try the following in order:

    # - stopping and removing all downloaded container images
    # - ensuring you have the latest Docker Desktop version
    # - factory reset your Docker Desktop settings

    # If you are still running into issues please post in #help-infra-seg.
    platform: linux/amd64
  kafka:
    image: wurstmeister/kafka
    links:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_VERSION: "0.10.1.0"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

    # See platform comment above for amd64/arm64 troubleshooting
    platform: linux/amd64
  localstack:
    image: localstack/localstack:0.10.5
    ports:
    - "4567-4599:4567-4599"
    environment:
    - DEBUG=1
    - DEFAULT_REGION=us-west-2
    # See platform comment above for amd64/arm64 troubleshooting
    platform: linux/amd64
