version: 2
jobs:
  test:
    docker:
      - image: cimg/go:1.24.4
        environment:
          GO111MODULE: "on"
          DIGGER_TEST_KAFKA_ADDR: "kafka:9092"
          DIGGER_TEST_S3_ADDR: "http://localstack:4572"

      - image: wurstmeister/zookeeper
        name: zookeeper
        ports:
          - "2181:2181"

      - image: wurstmeister/kafka:2.11-0.10.2.2
        name: kafka
        ports:
          - "9092:9092"
        environment:
          KAFKA_VERSION: "0.10.1.0"
          KAFKA_ADVERTISED_HOST_NAME: kafka
          KAFKA_ADVERTISED_PORT: "9092"
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      - image: localstack/localstack:0.10.5
        name: localstack
        ports:
          - "4567-4599:4567-4599"
        environment:
          DEBUG: "1"
          DEFAULT_REGION: "us-west-2"

    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          docker_layer_caching: true
      - run:
          name: Run tests
          command: make test
      - run:
          name: Run Snyk
          environment:
            SNYK_LEVEL: 'FLHI'
          command: curl -sL https://raw.githubusercontent.com/segmentio/snyk_helpers/master/initialization/snyk.sh | sh

workflows:
  version: 2
  run:
    jobs:
      - test:
          context: snyk
          filters:
            tags:
              only: /.*/
